// Generate src/seed/marketing-os-skill-seed.ts from the VENDORED marketing-os sources
// (vendor/marketing-os/ — byte-verbatim upstream, see its README) + the NeuraMesh manifest
// (scripts/marketing-os-manifest.ts: which modules become which skills, and the preamble that
// adapts each to the platform — brand docs for brand-context.md, artifacts for loose files,
// legs for subagents, the enforced report shape).
//
// gen-skill-seed clones live repos at generate time; this one reads the vendored copy so the
// seed is reproducible offline and the upstream pin is explicit. Run:
//   pnpm --filter @neuramesh/control-api gen:marketing-os-seed
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { MARKETING_OS_PACK, MARKETING_OS_PREAMBLES, MARKETING_OS_SKILLS } from './marketing-os-manifest';

// the same body cap as gen-skill-seed — the seed + per-member sync stay light + agent-loadable
const CAP = 32_000;
const UPSTREAM_REF = 'bb67dff5f04b'; // vendor/marketing-os/README.md carries the full pin
// vendor/community-skills/README.md carries these two (content-creator @ awesome-llm-apps, ugc-strategy @ everything-claude-marketing)
const COMMUNITY_REF = 'ca3a3d37+453d32d4';

const root = join(import.meta.dirname ?? __dirname, '..');
const vendor = join(root, 'vendor', 'marketing-os', 'references');
const community = join(root, 'vendor', 'community-skills');

function composeBody(spec: (typeof MARKETING_OS_SKILLS)[number]): string {
  const preamble = MARKETING_OS_PREAMBLES[spec.preamble];
  const parts = spec.sources.map((f, i) => {
    const raw = readFileSync(join(spec.root === 'community-skills' ? community : vendor, f), 'utf8');
    // a community SKILL.md carries YAML frontmatter (name, description, licence); the seed keeps the body
    const text = (spec.root === 'community-skills' ? raw.replace(/^---\n[\s\S]*?\n---\n/, '') : raw).trim();
    // the gen-skill-seed companion idiom: later files inline under a labelled divider so one
    // load_skill call carries the module AND its rubric/spec sheet
    return i === 0 ? text : `\n\n---\n\n# ${f} (companion file — inlined)\n\n${text}`;
  });
  const body = `${preamble}${parts.join('')}`;
  return body.length > CAP ? `${body.slice(0, CAP)}\n\n…(truncated — full module in vendor/marketing-os)` : body;
}

const skills = MARKETING_OS_SKILLS.map((s) => ({
  name: s.name,
  description: s.description,
  body: composeBody(s),
}));

const pack = {
  name: MARKETING_OS_PACK.name,
  description: MARKETING_OS_PACK.description,
  source_url: 'https://github.com/Yuzzyuk/marketing-os',
  source_ref: 'main',
  version: `bundled@${UPSTREAM_REF}+${COMMUNITY_REF}`,
};

const out = `// GENERATED by scripts/gen-marketing-os-seed.ts — do not edit by hand.
// Source: vendor/marketing-os (${pack.source_url} @ ${UPSTREAM_REF}, MIT) + vendor/community-skills
// (@ ${COMMUNITY_REF}, see its README) + the NeuraMesh preambles in scripts/marketing-os-manifest.ts.
// Re-vendor + re-run to update.
import type { SeedPack } from './skill-seed';

export const MARKETING_OS_SKILL_SEED: SeedPack[] = ${JSON.stringify([{ pack, skills }], null, 2)};
`;

writeFileSync(join(root, 'src', 'seed', 'marketing-os-skill-seed.ts'), out);
const sizes = skills.map((s) => `${s.name} (${s.body.length})`).join(', ');
console.log(`marketing-os seed: ${skills.length} skills → src/seed/marketing-os-skill-seed.ts\n${sizes}`);
