// THE HARNESS'S MARKETING ROOM (split from mock-nm.ts for the size ratchet, the desk round
// 2026-09-17): the Acme marketing room's library — the brand docs and one row per LibPreview branch,
// exactly as mock-nm.ts carried them — plus the two rows the desk reads: a scored audit report (the
// tile's dial, the catalog row's fact) and an armed cadence (the `armed · weekly` tok). Flowe's room
// stays mid-setup with nothing, on purpose: the desk's three honest states are all on one screen.
import { PLAYBOOKS, playbookAsk } from '@neuramesh/shared';

const ago = (ms: number) => new Date(Date.now() - ms).toISOString();

export const marketingArtifacts = (channelId: string) => channelId !== 'c-marketing' ? [] : [
      { id: 'la-1', kind: 'doc', name: 'brand-guidelines.md', mime: 'text/markdown', inline_content: '# NeuraMesh · Brand guidelines\n\n**Mood:** warm, understated, analog-meets-digital. Intentionally different from the cold blues of AI tools.\n\n- Voice: dry, confident, developer-native\n- "→" as a recurring motif\n- Named agents have personalities', size_bytes: 1430, promoted: 1, message_id: null, task_id: 't-1204', created_at: new Date(Date.now() - 3 * 3600e3).toISOString() },
      { id: 'la-2', kind: 'doc', name: 'business-profile.md', mime: 'text/markdown', inline_content: '# NeuraMesh · Business profile\n\nAn AI agent orchestration platform for software teams.', size_bytes: 1470, promoted: 1, message_id: null, task_id: 't-1204', created_at: new Date(Date.now() - 3 * 3600e3).toISOString() },
      { id: 'la-3', kind: 'doc', name: 'social-strategy.md', mime: 'text/markdown', inline_content: '# NeuraMesh · Social strategy\n\nX first — developer audiences live there.', size_bytes: 2038, promoted: 1, message_id: null, task_id: 't-1204', created_at: new Date(Date.now() - 2 * 3600e3).toISOString() },
      { id: 'la-4', kind: 'screenshot', name: 'og-card-a.png', mime: 'image/png', inline_content: 'data:image/svg+xml;base64,' + btoa('<svg xmlns="http://www.w3.org/2000/svg" width="320" height="160"><rect width="320" height="160" fill="#2b2b2b"/><rect x="24" y="24" width="120" height="14" rx="7" fill="#8f8f8f"/><rect x="24" y="52" width="220" height="10" rx="5" fill="#565656"/><rect x="24" y="70" width="180" height="10" rx="5" fill="#565656"/></svg>'), size_bytes: 9000, promoted: 0, message_id: null, task_id: null, created_at: new Date(Date.now() - 1 * 3600e3).toISOString() },
      { id: 'la-5', kind: 'doc', name: 'twitter-2026-07-21.md', mime: 'text/markdown', inline_content: 'Draft: stateless agents are broken by design…', size_bytes: 244, promoted: 0, message_id: null, task_id: null, created_at: new Date(Date.now() - 30 * 60e3).toISOString() },
      // one row per LibPreview branch, so the harness proves the tiles render the FILE and not a
      // row of identical paperclips: design html · raw json · diff · a drawn post image
      { id: 'la-6', kind: 'design', name: 'design-mockup-v2-launch-card.html', mime: 'text/html', inline_content: '<!doctype html><html data-theme="dark"><head><style>body{margin:0;font:14px/1.5 system-ui;background:#111;color:#eee;padding:28px}h1{font-size:26px;margin:0 0 10px;letter-spacing:-.02em}p{color:#9a9a9a;margin:0 0 18px;max-width:44ch}.row{display:flex;gap:10px}.b{background:#e8dfd2;color:#111;border-radius:8px;padding:9px 16px;font-weight:600}.g{border:1px solid #333;border-radius:8px;padding:9px 16px;color:#bbb}.card{margin-top:26px;border:1px solid #2a2a2a;border-radius:12px;padding:16px;background:#171717}</style></head><body><h1>Your people. Your agents.</h1><p>One room where the whole team — human and otherwise — plans, builds and ships together.</p><div class="row"><span class="b">Start free</span><span class="g">Watch the loop</span></div><div class="card"><b>#build</b><p style="margin:6px 0 0">rex handed #1031 to plume · 2 agents working</p></div></body></html>', size_bytes: 980, promoted: 1, message_id: null, task_id: 't-1204', created_at: new Date(Date.now() - 5 * 3600e3).toISOString() },
      { id: 'la-7', kind: 'file', name: 'posts.json', mime: 'application/json', inline_content: '[\n  {\n    "platform": "x",\n    "body": "Body wrecked, mind still sprinting through tomorrow\'s standup.",\n    "imageBrief": "warm gold key light on near-black, a desk at dusk",\n    "note": "Mon · pain→solution · image · 217/280"\n  },\n  {\n    "platform": "x",\n    "body": "NSDR isn\'t \\"lying down with an app.\\" It\'s a specific protocol.",\n    "note": "Tue · education · no image · 227/280"\n  }\n]', size_bytes: 412, promoted: 0, message_id: null, task_id: 't-1204', created_at: new Date(Date.now() - 90 * 60e3).toISOString() },
      { id: 'la-8', kind: 'diff', name: 'library-previews.diff', mime: 'text/x-diff', inline_content: 'diff --git a/tokens.css b/tokens.css\n@@ -400,7 +400,7 @@\n-.mklibgrid { grid-template-columns: repeat(auto-fill, minmax(150px, 1fr)); }\n-.mklthumb { display: grid; place-items: center; height: 76px; }\n+.mklibgrid { grid-template-columns: repeat(auto-fill, minmax(186px, 1fr)); }\n+.mklthumb { position: relative; display: block; height: 132px; }\n+.mklpmd { display: block; padding: 8px 10px; font-size: 9.5px; }', size_bytes: 380, promoted: 0, message_id: null, task_id: 't-1204', created_at: new Date(Date.now() - 100 * 60e3).toISOString() },
      // shaped exactly as main/sync.ts now PROJECTS a drawn post image (kind 'image' is a library
      // label, not an artifact_kind — the bytes never leave content_media)
      { id: 'la-9', kind: 'image', name: 'Body wrecked, mind still sprinting through…', mime: 'image/jpeg', inline_content: 'data:image/svg+xml;base64,' + btoa('<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300"><defs><linearGradient id="s" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#c98a4b"/><stop offset="1" stop-color="#1a1410"/></linearGradient></defs><rect width="400" height="300" fill="url(#s)"/><circle cx="300" cy="70" r="34" fill="#f0c98a" opacity=".8"/><rect x="0" y="210" width="400" height="90" fill="#0d0a08" opacity=".85"/><rect x="150" y="150" width="60" height="70" rx="26" fill="#0d0a08"/></svg>'), size_bytes: 96_000, promoted: 0, message_id: null, task_id: 't-1204', created_at: new Date(Date.now() - 45 * 60e3).toISOString() },
      // the desk's scored state: a report the way shared/reports.ts parses one (title, the score line in
      // the head, the gaps section), named the way playbookOfReport recognises it
      { id: 'la-10', kind: 'file', name: 'audit-report-2026-09-14.md', mime: 'text/markdown', inline_content: '# Site & funnel audit \u00b7 flowe.app\n2026-09-14 \u00b7 Score: 72/100 \u00b7 Basis: the live site, the pricing page, one product page\n\n## Scorecard\n| Dimension | Score |\n|---|---|\n| Messaging | 78 |\n| Conversion | 64 |\n\n## Fix these first\n1. The hero names the category, not the pain.\n\n## What\u2019s already working\n- The pricing page loads fast.\n\n## What I couldn\u2019t determine\n- Search traffic: no analytics access.', size_bytes: 640, promoted: 0, message_id: null, task_id: 'tk-1005', created_at: ago(3 * 86_400e3) },
    ];

/** an armed playbook cadence in the marketing room — the prompt is the ask, so playbookFromAsk finds it */
export const marketingSchedules = [
  { id: 'sch-mk-1', channelId: 'c-marketing', title: 'Reply radar, weekly', prompt: playbookAsk(PLAYBOOKS.find((p) => p.id === 'engage')!), cadence: 'weekly', at_time: '09:00', tz: 'America/Vancouver', next_run_at: ago(-5 * 86_400e3), status: 'active', weekday: 1 },
];
