import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, symlinkSync, unlinkSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  collectEngineeringChanges,
  createEngineeringChangeRefresh,
  MAX_ENGINEERING_CHANGE_EVENT_BYTES,
  MAX_ENGINEERING_CHANGE_FILES,
} from './engineering-changes';
import type { EngineeringRuntimeChange } from '../../engineering-protocol';
import { gitChildEnv } from '../harness/workspaces';

test('authoritative Engineering changes include command-created and edited files', async () => {
  const cwd = mkdtempSync('/tmp/nm-engineering-changes-');
  const git = (args: string[]) => execFileSync('git', args, { cwd, env: gitChildEnv() });
  git(['init', '-q', '-b', 'main']);
  git(['config', 'user.email', 'test@neuramesh.local']);
  git(['config', 'user.name', 'NeuraMesh Test']);
  mkdirSync(join(cwd, 'src'));
  writeFileSync(join(cwd, 'src', 'tracked.ts'), 'old\n');
  git(['add', '.']); git(['commit', '-qm', 'initial']);
  writeFileSync(join(cwd, 'src', 'tracked.ts'), 'new\n');
  writeFileSync(join(cwd, 'src', 'generated.ts'), 'generated by command\n');
  const changes = await collectEngineeringChanges(cwd);
  assert.deepEqual(changes.map((change) => [change.path, change.kind]), [['src/generated.ts', 'added'], ['src/tracked.ts', 'modified']]);
  assert.match(changes[0]!.diff, /generated by command/);
  assert.match(changes[1]!.diff, /-old/);
});

test('Engineering change refreshes serialize and coalesce while a scan is running', async () => {
  const releases: Array<() => void> = [];
  let scans = 0;
  const emitted: EngineeringRuntimeChange[][] = [];
  const refresh = createEngineeringChangeRefresh('/repo', (changes) => emitted.push(changes), (error) => assert.fail(String(error)), async () => {
    scans += 1;
    await new Promise<void>((resolve) => releases.push(resolve));
    return [];
  });
  refresh(); refresh(); refresh();
  assert.equal(scans, 1);
  releases.shift()!();
  await new Promise((resolve) => setTimeout(resolve, 0));
  assert.equal(scans, 2);
  releases.shift()!();
  await new Promise((resolve) => setTimeout(resolve, 0));
  assert.equal(emitted.length, 2);
});

test('Engineering changes never follow untracked symlinks outside the worktree', async () => {
  const base = mkdtempSync('/tmp/nm-engineering-change-link-');
  const cwd = join(base, 'repo');
  mkdirSync(cwd);
  const git = (args: string[]) => execFileSync('git', args, { cwd, env: gitChildEnv() });
  git(['init', '-q', '-b', 'main']);
  git(['config', 'user.email', 'test@neuramesh.local']);
  git(['config', 'user.name', 'NeuraMesh Test']);
  writeFileSync(join(cwd, 'README.md'), 'fixture\n');
  git(['add', '.']); git(['commit', '-qm', 'initial']);
  writeFileSync(join(base, 'secret.txt'), 'machine credential material\n');
  symlinkSync(join(base, 'secret.txt'), join(cwd, 'leak.txt'));
  const changes = await collectEngineeringChanges(cwd);
  assert.equal(changes.some((change) => change.path === 'leak.txt'), false);
  assert.doesNotMatch(JSON.stringify(changes), /machine credential material/);
});

test('Engineering changes reject tracked FIFOs without blocking the scan', async () => {
  const cwd = mkdtempSync('/tmp/nm-engineering-change-fifo-');
  const git = (args: string[]) => execFileSync('git', args, { cwd, env: gitChildEnv() });
  git(['init', '-q', '-b', 'main']); git(['config', 'user.email', 'test@neuramesh.local']); git(['config', 'user.name', 'NeuraMesh Test']);
  writeFileSync(join(cwd, 'tracked.txt'), 'fixture\n'); git(['add', '.']); git(['commit', '-qm', 'initial']);
  unlinkSync(join(cwd, 'tracked.txt')); execFileSync('mkfifo', [join(cwd, 'tracked.txt')]);

  const changes = await collectEngineeringChanges(cwd);
  assert.equal(changes.some((change) => change.path === 'tracked.txt'), false);
});

test('Engineering changes classify empty files by existence instead of content truthiness', async () => {
  const cwd = mkdtempSync('/tmp/nm-engineering-empty-changes-');
  const git = (args: string[]) => execFileSync('git', args, { cwd, env: gitChildEnv() });
  git(['init', '-q', '-b', 'main']); git(['config', 'user.email', 'test@neuramesh.local']); git(['config', 'user.name', 'NeuraMesh Test']);
  writeFileSync(join(cwd, 'tracked.txt'), 'content\n'); writeFileSync(join(cwd, 'empty-before.txt'), '');
  git(['add', '.']); git(['commit', '-qm', 'initial']);
  writeFileSync(join(cwd, 'tracked.txt'), ''); writeFileSync(join(cwd, 'empty-before.txt'), 'now populated\n'); writeFileSync(join(cwd, 'new-empty.txt'), '');
  const changes = await collectEngineeringChanges(cwd);
  assert.deepEqual(changes.map(({ path, kind }) => [path, kind]), [['empty-before.txt', 'modified'], ['new-empty.txt', 'added'], ['tracked.txt', 'modified']]);
});

test('Engineering changes keep oversized files visible while capping their preview bodies', async () => {
  const cwd = mkdtempSync('/tmp/nm-engineering-large-changes-');
  const git = (args: string[]) => execFileSync('git', args, { cwd, env: gitChildEnv() });
  git(['init', '-q', '-b', 'main']); git(['config', 'user.email', 'test@neuramesh.local']); git(['config', 'user.name', 'NeuraMesh Test']);
  writeFileSync(join(cwd, 'README.md'), 'fixture\n'); git(['add', '.']); git(['commit', '-qm', 'initial']);
  writeFileSync(join(cwd, 'large.bin'), Buffer.alloc(2 * 1024 * 1024 + 1, 1));
  const [change] = await collectEngineeringChanges(cwd);
  assert.deepEqual({ path: change?.path, kind: change?.kind, after: change?.after }, { path: 'large.bin', kind: 'added', after: '[file too large to preview]' });
  assert.equal((change?.diff.length ?? 0) <= 2 * 1024 * 1024 + 20, true);
});

test('Engineering change events cap aggregate bytes and report omitted files', async () => {
  const cwd = mkdtempSync('/tmp/nm-engineering-many-changes-');
  const git = (args: string[]) => execFileSync('git', args, { cwd, env: gitChildEnv() });
  git(['init', '-q', '-b', 'main']); git(['config', 'user.email', 'test@neuramesh.local']); git(['config', 'user.name', 'NeuraMesh Test']);
  writeFileSync(join(cwd, 'README.md'), 'fixture\n'); git(['add', '.']); git(['commit', '-qm', 'initial']);
  for (let index = 0; index < MAX_ENGINEERING_CHANGE_FILES + 5; index += 1) writeFileSync(join(cwd, `generated-${index}.txt`), 'generated\n');

  const changes = await collectEngineeringChanges(cwd);
  assert.equal(changes.length, MAX_ENGINEERING_CHANGE_FILES);
  assert.match(changes.at(-1)?.path ?? '', /additional changes omitted/);
  assert.equal(Buffer.byteLength(JSON.stringify(changes)) <= MAX_ENGINEERING_CHANGE_EVENT_BYTES + 1024, true);
});
