// Image generation for marketing drafts (marketing-workflow §4.6). The marketer describes the
// visual it wants; this turns that description into actual pixels, on the machine, with the
// machine's own provider key — the same BYOK shape every runtime already uses. Keys never leave
// here and the generated bytes never leave the user's disk.
//
// No top-level electron import: this module is in the desktop test glob, and requiring 'electron'
// on a binary-less CI runner throws. nativeImage arrives lazily in the one thumbnail branch.

import type { ImageSpec } from '@neuramesh/shared';
import { sniffImageMime } from '@neuramesh/shared';

export type GeneratedImage = { mime: string; bytes: Buffer };
export type ImageCred = { provider: 'openai' | 'gemini'; key: string };
export type GenResult = { image?: GeneratedImage; error?: string; model?: string };

/**
 * Best-first, per provider. Access varies by account — a key that can't see the newest model
 * should still get a picture — so these are LADDERS: we try the best one this connection can
 * actually reach and fall to the next only when the model is unavailable to it (never on a
 * content refusal, which would just burn the same rejection again).
 *
 * openai — gpt-image-2 is OpenAI's stated default for new builds (Apr 2026); 1.5 and 1 are the
 *   fallbacks for accounts without it.
 * gemini — gemini-3.1-flash-image is "Nano Banana 2", the generalist workhorse Google recommends
 *   for most work; 2.5-flash-image is the legacy model it replaced.
 */
export const IMAGE_MODELS: Record<'openai' | 'gemini', readonly string[]> = {
  openai: ['gpt-image-2', 'gpt-image-1.5', 'gpt-image-1'],
  gemini: ['gemini-3.1-flash-image', 'gemini-2.5-flash-image'],
};

// "this key can't use that model" → try the next rung. Anything else (safety refusal, bad
// request, rate limit) is the answer, not a reason to pay for the same call again.
const unavailable = (status: number, msg: string): boolean =>
  status === 404 || ((status === 400 || status === 403) && /model|not found|does not exist|do not have access|not available|unsupported/i.test(msg));

const GEN_TIMEOUT_MS = 600_000; // gpt-image-2 at high quality runs 1–3min, longer under load; a generous 10min ceiling so a slow-but-real image is never cut off (a genuinely stuck call still aborts)
const GEN_MAX_BYTES = 12_000_000;

/**
 * Which image provider this machine can actually use, in preference order. gpt-image-1 first:
 * it holds a stated palette and honours "no lettering" far more reliably, which is the whole
 * job here. Mirrors keyEnvFor (runtime/adapter.ts) so a user who already runs Codex or Gemini
 * agents needs no new key and no new setting.
 */
export function pickImageProvider(env: NodeJS.ProcessEnv = process.env): ImageCred | null {
  const openai = env['OPENAI_API_KEY'] || env['CODEX_API_KEY'];
  if (openai) return { provider: 'openai', key: openai };
  const gemini = env['GEMINI_API_KEY'] || env['GOOGLE_API_KEY'];
  if (gemini) return { provider: 'gemini', key: gemini };
  return null;
}

function decode(b64: string, mime: string): GenResult {
  const bytes = Buffer.from(b64, 'base64');
  if (!bytes.length) return { error: 'provider returned an empty image' };
  if (bytes.length > GEN_MAX_BYTES) return { error: `image too large (${bytes.length} bytes)` };
  // the BYTES outrank the declaration: the openai path used to hardcode png and gemini's
  // mimeType is the provider's word — either lie survives storage and /media serving, then
  // dies at X's finalize as "media type unrecognized". Magic numbers are the truth.
  return { image: { mime: sniffImageMime(new Uint8Array(bytes.subarray(0, 16))) ?? mime, bytes } };
}

/**
 * Generate one image. Returns the bytes, or an `error` string explaining why not — never throws
 * and never partially succeeds, because a missing image must degrade the draft to "needs image",
 * not fail the marketer's whole task.
 */
async function generateOn(spec: ImageSpec, cred: ImageCred, model: string, fetchFn: typeof fetch): Promise<GenResult & { next?: boolean }> {
  const signal = AbortSignal.timeout(GEN_TIMEOUT_MS);
  try {
    if (cred.provider === 'openai') {
      const res = await fetchFn('https://api.openai.com/v1/images/generations', {
        method: 'POST',
        headers: { 'content-type': 'application/json', authorization: `Bearer ${cred.key}` },
        // output_format pinned: the model's server default decides otherwise (gpt-image-2 can answer
        // webp), and a declared-vs-actual drift surfaces days later as X's "media type unrecognized"
        body: JSON.stringify({ model, prompt: spec.prompt, size: spec.size, n: 1, quality: 'high', output_format: 'png' }),
        signal,
      });
      const j = (await res.json().catch(() => null)) as { data?: Array<{ b64_json?: string }>; error?: { message?: string } } | null;
      if (!res.ok) {
        const msg = j?.error?.message ?? `openai ${res.status}`;
        return { error: msg, next: unavailable(res.status, msg) };
      }
      const b64 = j?.data?.[0]?.b64_json;
      return b64 ? { ...decode(b64, 'image/png'), model } : { error: 'openai returned no image data' };
    }

    // key rides a HEADER, never the query string (query params leak into logs and proxies).
    // responseModalities is REQUIRED for image output on generateContent — without it the model
    // answers with text and you get a "returned no image data" that looks like a model problem.
    const res = await fetchFn(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`, {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'x-goog-api-key': cred.key },
      body: JSON.stringify({
        contents: [{ parts: [{ text: spec.prompt }] }],
        generationConfig: { responseModalities: ['TEXT', 'IMAGE'] },
      }),
      signal,
    });
    const j = (await res.json().catch(() => null)) as {
      candidates?: Array<{ content?: { parts?: Array<{ inlineData?: { mimeType?: string; data?: string } }> } }>;
      error?: { message?: string };
    } | null;
    if (!res.ok) {
      const msg = j?.error?.message ?? `gemini ${res.status}`;
      return { error: msg, next: unavailable(res.status, msg) };
    }
    const part = j?.candidates?.[0]?.content?.parts?.find((p) => p.inlineData?.data);
    return part?.inlineData?.data
      ? { ...decode(part.inlineData.data, part.inlineData.mimeType ?? 'image/png'), model }
      : { error: 'gemini returned no image data' };
  } catch (e) {
    return { error: (e as Error).name === 'TimeoutError' ? 'image generation timed out' : (e as Error).message };
  }
}

/**
 * Generate one image on the best model this connection can reach, walking the provider's ladder.
 * Returns the bytes and WHICH model drew them, or an `error` explaining why not — never throws
 * and never partially succeeds, because a missing image must degrade the draft to "needs image",
 * not fail the marketer's whole task.
 */
export async function generateImage(spec: ImageSpec, cred: ImageCred, fetchFn: typeof fetch = fetch, models: readonly string[] = IMAGE_MODELS[cred.provider]): Promise<GenResult> {
  let last: GenResult = { error: `no image model configured for ${cred.provider}` };
  for (const model of models) {
    const r = await generateOn(spec, cred, model, fetchFn);
    if (r.image) return { image: r.image, model: r.model };
    last = { error: r.error };
    if (!r.next) break; // a real answer (refusal, rate limit, bad request) — not a reason to retry
  }
  return last;
}

// The card thumbnail. content_items.media replicates to every client, so the inline preview is a
// downscaled JPEG (the 0048 chat-attachment precedent: thumbnail travels, full bytes stay local).
const THUMB_DIM = 640; // the inline card renders ~300px wide, so 640 covers @2x
const THUMB_MAX = 140_000; // base64 chars — the replica budget for one draft's preview

export type ImageVerdict = { ok: boolean; fix?: string };

// The marketer owns the post, so it eyeballs the render before it rides the draft. Deliberately
// PERMISSIVE: this is a basics check, not an art critique — a picture that is merely not the one
// we'd have picked still ships, because the human reviews every card before anything publishes.
const REVIEW_ASK = (direction: string): string =>
  `You are the marketer who commissioned this image for a social post. The art direction you gave was:\n\n"${direction}"\n\n` +
  `Look at the image and decide whether it is USABLE. Be permissive — pass it unless something would embarrass us if it went out: ` +
  `the wrong subject, garbled or misspelled lettering, colours plainly off the brand palette, or a composition that cannot be posted. ` +
  `Small imperfections and choices you merely disagree with are fine.\n\n` +
  `Reply with exactly OK, or one short sentence naming the single biggest fix.`;

const verdictFrom = (text: string): ImageVerdict => {
  const t = (text ?? '').trim();
  if (!t || /^ok\b/i.test(t) || /^"?ok"?[.!]?$/i.test(t)) return { ok: true };
  return { ok: false, fix: t.replace(/^[-*\s]+/, '').slice(0, 300) };
};

/**
 * Ask the marketer's seat to look at what came back. Any failure — no key, a 500, an unparseable
 * answer — returns OK: a broken check must never hold up a draft, and the human still sees the
 * picture on the card before it can publish.
 */
export async function reviewImage(cred: ImageCred, model: string, artDirection: string, image: GeneratedImage, fetchFn: typeof fetch = fetch): Promise<ImageVerdict> {
  if (!model || !artDirection.trim()) return { ok: true };
  const b64 = image.bytes.toString('base64');
  try {
    if (cred.provider === 'openai') {
      const res = await fetchFn('https://api.openai.com/v1/chat/completions', {
        method: 'POST',
        headers: { 'content-type': 'application/json', authorization: `Bearer ${cred.key}` },
        body: JSON.stringify({
          model,
          messages: [{ role: 'user', content: [
            { type: 'text', text: REVIEW_ASK(artDirection) },
            { type: 'image_url', image_url: { url: `data:${image.mime};base64,${b64}` } },
          ] }],
        }),
        signal: AbortSignal.timeout(60_000),
      });
      if (!res.ok) return { ok: true };
      const j = (await res.json()) as { choices?: Array<{ message?: { content?: string } }> };
      return verdictFrom(j.choices?.[0]?.message?.content ?? '');
    }
    const res = await fetchFn(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(cred.key)}`, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ contents: [{ parts: [{ text: REVIEW_ASK(artDirection) }, { inlineData: { mimeType: image.mime, data: b64 } }] }] }),
      signal: AbortSignal.timeout(60_000),
    });
    if (!res.ok) return { ok: true };
    const j = (await res.json()) as { candidates?: Array<{ content?: { parts?: Array<{ text?: string }> } }> };
    return verdictFrom(j.candidates?.[0]?.content?.parts?.map((p) => p.text ?? '').join(' ') ?? '');
  } catch {
    return { ok: true };
  }
}

// One TEXT-ONLY completion on the image credential (calendar-image-gen round: brief-writing,
// re-angling). The image key already powers the review pass above; running the words on the
// same key keeps the credential story singular — "no image key" is the one failure for
// everything the draft-image button does. Throws on a non-2xx so callers surface it.
export async function textComplete(cred: ImageCred, model: string, system: string, user: string, fetchFn: typeof fetch = fetch): Promise<string> {
  if (cred.provider === 'openai') {
    const res = await fetchFn('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: { 'content-type': 'application/json', authorization: `Bearer ${cred.key}` },
      body: JSON.stringify({ model, messages: [{ role: 'system', content: system }, { role: 'user', content: user }] }),
      signal: AbortSignal.timeout(60_000),
    });
    if (!res.ok) throw new Error(`completion failed ${res.status}`);
    const j = (await res.json()) as { choices?: Array<{ message?: { content?: string } }> };
    return j.choices?.[0]?.message?.content ?? '';
  }
  const res = await fetchFn(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(cred.key)}`, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ systemInstruction: { parts: [{ text: system }] }, contents: [{ parts: [{ text: user }] }] }),
    signal: AbortSignal.timeout(60_000),
  });
  if (!res.ok) throw new Error(`completion failed ${res.status}`);
  const j = (await res.json()) as { candidates?: Array<{ content?: { parts?: Array<{ text?: string }> } }> };
  return j.candidates?.[0]?.content?.parts?.map((p) => p.text ?? '').join(' ') ?? '';
}

// The copy that actually publishes (0090): hosted server-side, fetched by Meta / uploaded to X.
// Always JPEG — it is the one format every network accepts — and inside X's 5MB image ceiling,
// which is the tightest of the three.
const PUBLISH_DIM = 2048;
const PUBLISH_MAX = 4_800_000;

export async function publishDataUrl(bytes: Buffer): Promise<string | null> {
  try {
    const { nativeImage } = await import('electron');
    const img = nativeImage.createFromBuffer(bytes);
    if (img.isEmpty()) return null;
    const { width, height } = img.getSize();
    const long = Math.max(width, height);
    if (!long) return null;
    const sized = long > PUBLISH_DIM ? img.resize({ width: Math.round((width * PUBLISH_DIM) / long), quality: 'best' }) : img;
    for (const q of [88, 75, 60]) {
      const jpeg = sized.toJPEG(q);
      if (jpeg.length <= PUBLISH_MAX) return `data:image/jpeg;base64,${jpeg.toString('base64')}`;
    }
    return null; // still too big to publish anywhere — better to say so than to host a dud
  } catch {
    return null;
  }
}

// A shelf copy (the product shots, video-rung plan §9): an image an agent made lands on the room's
// shelf as a data URI inside `artifact.create`'s 300k-character cap, at a size the film's product
// frame can hold at 720 px wide. JPEG, the long side to 1280, the quality ladder until it fits.
const SHELF_DIM = 1280;
const SHELF_MAX = 300_000;

export async function shelfDataUrl(bytes: Buffer): Promise<string | null> {
  try {
    const { nativeImage } = await import('electron');
    const img = nativeImage.createFromBuffer(bytes);
    if (img.isEmpty()) return null;
    const { width, height } = img.getSize();
    const long = Math.max(width, height);
    if (!long) return null;
    const sized = long > SHELF_DIM ? img.resize({ width: Math.round((width * SHELF_DIM) / long), quality: 'best' }) : img;
    for (const q of [82, 68, 55, 42]) {
      const url = `data:image/jpeg;base64,${sized.toJPEG(q).toString('base64')}`;
      if (url.length <= SHELF_MAX) return url;
    }
    return null;
  } catch {
    return null;
  }
}

export async function thumbDataUrl(bytes: Buffer): Promise<string | null> {
  try {
    const { nativeImage } = await import('electron');
    const img = nativeImage.createFromBuffer(bytes);
    if (img.isEmpty()) return null;
    const { width, height } = img.getSize();
    const long = Math.max(width, height);
    if (!long) return null;
    const small = long > THUMB_DIM ? img.resize({ width: Math.round((width * THUMB_DIM) / long), quality: 'good' }) : img;
    for (const q of [78, 60, 45]) {
      const url = `data:image/jpeg;base64,${small.toJPEG(q).toString('base64')}`;
      if (url.length <= THUMB_MAX) return url;
    }
    return null; // still oversize — better no preview than a bloated replica
  } catch {
    return null;
  }
}
